### PR TITLE
feat: add query parameters for assets search

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by polomani** [comment]
was it released? I don't see it in docs

**Comment by ghost** [comment]
I think so, I think Eric released this like last week?

**Comment by ghost** [comment]
yeep, its in the docs now :)
https://docs.cognite.com/api/v1/#operation/searchAssets
https://docs.cognite.com/api/v1/#operation/searchTimeSeries

**Review by polomani — APPROVED** [review]

**Comment by polomani** [comment]
thanks!

**Pull request merged**
