### PR TITLE
test: increase global timeout for tests

### PR DESCRIPTION
**Pull request by andersfylling**

### CODE REVIEW

**Comment by henrist** [comment]
See https://cognitedata.slack.com/archives/G011ZCXB2BE/p1642501541011700?thread_ts=1642500317.011100&cid=G011ZCXB2BE

In general I wouldn't expect any of our API endpoints except document preview to take more than 5 seconds? Do you have any examples of failures?

If we have issues with timeouts in general we might also consider changing https://jestjs.io/docs/configuration#testtimeout-number

**Comment by andersfylling** [comment]
There are several cases where our tests fail due to timeouts. People have also sent me messages about the tests failing due to time outs. 

This has also happened for other services, and the direct cause isn't known as of now.

**Comment by henrist** [comment]
> This has also happened for other services, and the direct cause isn't known as of now.

Then it sounds like it makes sense to increase the general timeout instead of doing it individually? I think the int tests should ideally run separately from the others so they can also have their own config, but that can be looked more into later.

**Comment by henrist** [comment]
Here's an example of timeout for another service: https://github.com/cognitedata/cognite-sdk-js/runs/4894382847?check_suite_focus=true

**Review by henrist — APPROVED** [review]
I think this makes sense. :+1:

It would be nice if the commit/merge message explains the background/reason for this, so that is easily available when checking the line commit message.

**Comment by andersfylling** [comment]
Good point! I'll update the commit description

**Review by pedroharbs — APPROVED** [review]

**Pull request merged**
