### PR TITLE
feat:  move vision extract api to v1

### PR DESCRIPTION
**Pull request by marvrez**
Jira link:

[VIS-1060](https://cognitedata.atlassian.net/browse/VIS-1060)

Description:

Moves the vision extract API from playground to V1. A separate PR will be made for adding support for beta features (https://github.com/cognitedata/cognite-sdk-js/pull/873)

### CODE REVIEW

**Comment by andersfylling** [comment]
> [packages/playground/src/.cognite-openapi-snapshot.json](https://github.com/cognitedata/cognite-sdk-js/pull/872/files#diff-a0f576f952ed893495382d87cb2a7ac6353abed9240e6e3543d7aaae46994a37)

This snapshot file is used by services in the package to generate types, it should not be removed. Added https://github.com/cognitedata/cognite-sdk-js/pull/871 to help simplify manually updating files. Easiest way to remove vision is probably to just delete the vision package in playground and run `yarn codegen generate-types --package=playground` to update the export/import statements.

**Review by andersfylling — APPROVED** [review]

**Review by miladcognite — COMMENTED** [review]
How is the beta flag in headers handled?

**Comment by marvrez** [comment]
It isnt handles yet. Will be added in a separate PR (as per the PR description)

**Comment by miladcognite** [comment]
> It isnt handles yet. Will be added in a separate PR (as per the PR description)

Ah...sorry. Missed that.

**Review by miladcognite — APPROVED** [review]
LGTM :rocket:

**Pull request merged**
