### PR TITLE
docs: javascript doc v1 fix tests

### PR DESCRIPTION
**Pull request by digaomilleniun**

### CODE REVIEW

**Comment by BugGambit** [comment]
Looks good. Can you update the PR title to conform to the Angular git commit message convention (`docs: [subject]`)?

**Comment by BugGambit** [comment]
@digaomilleniun I believe the title should be "docs: ...". (not "feat: ..."). "feat" is reserved for new features for our users like a new endpoint, a new login option, etc. "docs" is used for improvements in the documentation.

**Comment by polomani** [comment]
@digaomilleniun updating docs is not a feature. use `docs: `

**Review by BugGambit — APPROVED** [review]
LGTM

**Pull request merged**
