### PR TITLE
feat(documents): classifier name

### PR DESCRIPTION
**Pull request by tommythorsen**
Add an optional name field to the document classifier.

### CODE REVIEW

**Review by andersfylling — APPROVED** [review]

**Comment by tommythorsen** [comment]
@andersfylling do you know why the `tests (10.x)` does not work? It doesn't even seem to be running

**Comment by tommythorsen** [comment]
Could it be related to the node-version changes in https://github.com/cognitedata/cognite-sdk-js/pull/708, @vegardok?

**Comment by andersfylling** [comment]
Hmm 10.x should have been removed. Could be bugged, might just need a
forced rerun

**Comment by tommythorsen** [comment]
I've done a few runs already, since I've been updating the PR a bit. I could try opening a new PR

**Comment by tommythorsen** [comment]
I tried a new PR here: https://github.com/cognitedata/cognite-sdk-js/pull/712, but it has the same problem

**Comment by andersfylling** [comment]
Uncertain how to fix this, as it's a github ci bug. All tests are technically green, so I'm going to merge this. This bug happens in every other PR as well, so the problem won't spread by merging this somehow.

**Comment by andersfylling** [comment]
And I found the issue: the branch protection required node v10.x to be successful for a merge.

**Comment by tommythorsen** [comment]
> And I found the issue: the branch protection required node v10.x to be successful for a merge.

Thanks for your help! 🙏

**Pull request merged**
