### PR TITLE
feat: update renovate bot set up

### PR DESCRIPTION
**Pull request by borajimin**
* only create prs after running the tests
* rebase only when the PR is behind branch

### CODE REVIEW

**Comment by andersfylling** [comment]
> Let me know if you just want the following in a different PR.

I want some addition behavior in here:
 - ~Only introduce a PR 3 days after its release~: 
   - this reduces the chance of spam as frequent updates tend to be delayed
   - It allows potential bug fixes to happen before we start using it
 - Only do updates during the weekends:
   - It's spamming my email and github notifications during work, and I'd like this be done when I'm not busy. 
   
 - https://docs.renovatebot.com/key-concepts/scheduling/#scheduling-syntax
 - https://docs.renovatebot.com/configuration-options/#stabilitydays

**Comment by borajimin** [comment]
> > Let me know if you just want the following in a different PR.
> 
> I want some addition behavior in here:
> 
> * Only introduce a PR 3 days after its release:
>   
>   * this reduces the chance of spam as frequent updates tend to be delayed
>   * It allows potential bug fixes to happen before we start using it
> * Only do updates during the weekends:
>   
>   * It's spamming my email and github notifications during work, and I'd like this be done when I'm not busy.
> * https://docs.renovatebot.com/key-concepts/scheduling/#scheduling-syntax
> * https://docs.renovatebot.com/configuration-options/#stabilitydays

Good idea :) Will add the following rules. Just let me know if you have any other rules that pops up. Thanks for the links ;) and we already have the stabilityDays set up to 5 days. I can decrease it to 3 days.

**Comment by andersfylling** [comment]
5 days is great! Sorry, I didn't see that one.

**Comment by borajimin** [comment]
image
@andersfylling Instead of weekends, what do you think of early Monday mornings?

**Comment by andersfylling** [comment]
From experience it can take a bit of time to open up everything. If we also start auto approving and auto merging (which is common), then all of this noise could be handled in the weekend and we get greeted by a nicely updated repo on the monday morning to deal with any potential issues.

That's another setup elsewhere, and it's been working quite nicely.

**Comment by borajimin** [comment]
> From experience it can take a bit of time to open up everything. If we also start auto approving and auto merging (which is common), then all of this noise could be handled in the weekend and we get greeted by a nicely updated repo on the monday morning to deal with any potential issues.
> 
> That's another setup elsewhere, and it's been working quite nicely.

I can add the auto merging and auto approving if all of the tests pass. 
I am a little skeptical of auto-approving though. Do you think the existing tests are enough to catch potential bugs created by the deps update?

**Comment by andersfylling** [comment]
> I am a little skeptical of auto-approving though. Do you think the existing tests are enough to catch potential bugs created by the deps update?

That's a fair point, there could be something we haven't caught on. Let's revisit that later on, and just leave it for now. I haven't been active enough lately to give a clear answer on that.

**Comment by andersfylling** [comment]
Hopefully we get there one day and PRs can auto rebase/update and auto merge on success over the weekends :pray:

**Review by ghost — APPROVED** [review]

**Review by andersfylling — APPROVED** [review]

**Comment by andersfylling** [comment]
@borajimin any reason we are holding back on this?

**Comment by borajimin** [comment]
> @borajimin any reason we are holding back on this?

😬 didn't see this message last week. We were holding it off because of the CVE resolution effort in CDF UX group. We were working on the mitigating all security vulnerabilities that are either high or critical. So, I wanted as many PRs to be opened by renovate to help update the dependencies. Now that we are more or less done with the effort, I think it's time to merge it.

**Pull request merged**
