### PR TITLE
chore: remove wells sdk

### PR DESCRIPTION
**Pull request by Sollimann**
wells sdk has been moved to: https://github.com/cognitedata/cognite-wells-sdk-js

### CODE REVIEW

**Comment by andersfylling** [comment]
Just out of curiousity: why is wells moving into their own js sdk?

**Review by sighol — APPROVED** [review]

**Comment by Sollimann** [comment]
@andersfylling two reasons:

* We no longer depend on anything in the core sdk
* The core CI/CD pipeline is very slow and and the tests are brittle

**Comment by Sollimann** [comment]
Can I get an approval :+1: @andersfylling  ? :) Think I need approval from two different teams

**Comment by andersfylling** [comment]
> The core CI/CD pipeline is very slow and and the tests are brittle

I fixed this a few weeks ago. Talked to some tech leads that were related to flaky integration tests, and updated them to be skipped. Eg. for the playground package, it takes me 1 minute to run the tests. There is still the codecov test that takes a while, but that is only run for PRs.

https://github.com/cognitedata/cognite-sdk-js/pulls?q=author%3Aandersfylling++test

**Comment by andersfylling** [comment]
> Can I get an approval +1 @andersfylling ? :) Think I need approval from two different teams

sorry, didn't see this message. Looks like a clean removal for me :+1:

**Review by andersfylling — APPROVED** [review]

**Pull request merged**
