### PR TITLE
feat: create this to reflect the breaking change introduced by isoplan annotations

### PR DESCRIPTION
**Pull request by SudilHasithaCognite**
- This PR is created to replace the breaking change introduced by the PR which makes fileRef optional. https://github.com/cognitedata/cognite-sdk-js/pull/1103
- The changes are reverted in this [PR](https://github.com/cognitedata/cognite-sdk-js/pull/1118)

### CODE REVIEW

**Comment by BugGambit** [comment]
@SudilHasithaCognite looks like the version in the package.json was manually edited? Please don't do that.

This is a breaking change, which will bump major and should be coordinated across Cognite to bulk several breaking changes together.
Is this change still a priority? I am working on releasing a new major version of the SDK and I am looking into changes we want to include

**Review by BugGambit — CHANGES_REQUESTED** [review]
Let's not bump a major version like this and rather bulk several breaking changes. See my comment

**Comment by SudilHasithaCognite** [comment]
No, you can safely discard this if necessary. We initially thought this would be
significant enough for a version bump. After this
https://github.com/cognitedata/fusion/pull/6966/files we thought of not changing it. But @cemreyavuz and @G0nza1es mentioned it will be necessary in the long run to do so.

**Comment by BugGambit** [comment]
@SudilHasithaCognite I suggest we close this PR and leave the breaking change in the SDK. The harm seems low and we will soon release a new major version of the SDK.

**Pull request closed without merging**
