### PR TITLE
fix: don't send expired tokens to authorize in scheduleRenewal call

### PR DESCRIPTION
**Pull request by ghost**
When `sdk.Login.authorize` is called with cached id&access-tokens it will use them and make sure to renew the tokens before they expires.
But today they are sent in as parameters to the second call to `sdk.Login.authorize` which is wrong (see diff).

This causes this network flow: https://docs.google.com/document/d/1RqiGrs25Udk-7spBuQ-wwS35BLdTUOFUd4ZX9HAiZg4/edit?usp=sharing

### CODE REVIEW

**Review by Meemaw — APPROVED** [review]
LGTM. This doesn't fix the "getting kicked out" problem though?

**Comment by ghost** [comment]
Why not?

**Comment by Meemaw** [comment]
From the timeline in doc it seems like we are just using the expired token for some time (5 seconds?) and this PR fixes that?

The bigger problem is that the user gets redirected from `/charts/<chartId>` to `/charts` after some time. Does this PR somehow fix that?

**Comment by ghost** [comment]
The timeline in the doc showed us that the 5 seconds with 401 caused the griff-react component to end up in a bad state. With this PR the SDK will not throw 401s anymore caused my the renewal process.

Also is it true that the user was actually kicked out from `/charts<chartId>` to `/charts`? I haven't heard about that before

**Comment by Meemaw** [comment]
Yes, I had a talk with one customer who was experiencing this. I had a felling that this was the bug that we are dealing with here. @AadneAadland was present in that call as well.

**Comment by Meemaw** [comment]
Should we merge this?

**Comment by ghost** [comment]
@Meemaw This package will auto-deploy to npm now so available in a few min. Would be great if you could bump the SDK version in Insight to check if this resolves the issue.

**Pull request merged**
