### PR TITLE
feat: add types for template capabilities

### PR DESCRIPTION
**Pull request by mortenhillbom**

### CODE REVIEW

**Review by Tapped — APPROVED** [review]
LGTM

**Review by Tapped — APPROVED** [review]

**Review by agadacz — APPROVED** [review]
👍

**Comment by andersfylling** [comment]
You need to update your PR title to match the same constraints as commit messages

**Comment by mortenhillbom** [comment]
> You need to update your PR title to match the same constraints as commit messages

Aaaaah, that's it! Thanks! 🤦‍♂️

**Comment by andersfylling** [comment]
@mortenhillbom I adjusted the github workflow to trigger when the pr title is changed, so this should be responsive next time. If you push an empty commit or update your branch against master all tests will become successful.

**Review by andersfylling — APPROVED** [review]

**Pull request merged**
