### PR TITLE
feat: directoryPrefix filter for files [release]

### PR DESCRIPTION
**Pull request by andersfylling**
https://cognitedata.atlassian.net/browse/CDF-8667

### CODE REVIEW

**Review by maaland — CHANGES_REQUESTED** [review]
Nice! Maybe a test of upload and list with the `directory` field as well, to be safe?

**Comment by andersfylling** [comment]
> Nice! Maybe a test of upload and list with the `directory` field as well, to be safe?

I'm trying to avoid doing any business logic tests in general. Since the sdk should just have a valid skeleton of the datastructures, and it's up to the user to define the arguments, I prefer just validating the outgoing datastructures/format. Otherwise the sdk can break if there are any changes to behaviour in /files, blocking all other PR's. But maybe this does not matter much if it's in stable?

**Comment by maaland** [comment]
For sure, I agree, not talking about the business logic. It would be good to test that the `directory` field in the file datastructure works, not just the `directoryPrefix` filed in the file filter. 

Looks like the [file create test](https://github.com/cognitedata/cognite-sdk-js/blob/master/packages/stable/src/__tests__/api/files.int.spec.ts#L63) is skipped for some reason, but maybe you can add `directory` to the [update test](https://github.com/cognitedata/cognite-sdk-js/blob/master/packages/stable/src/__tests__/api/files.int.spec.ts#L144) ? Like what was done there when `geoLocation` was added.

**Comment by maaland** [comment]
Actually, are the tests in this file even run? I see that the top-level describe is [skipped](https://github.com/cognitedata/cognite-sdk-js/blob/master/packages/stable/src/__tests__/api/files.int.spec.ts#L17) 🤔

**Comment by andersfylling** [comment]
> Actually, are the tests in this file even run? I see that the top-level describe is [skipped](https://github.com/cognitedata/cognite-sdk-js/blob/master/packages/stable/src/__tests__/api/files.int.spec.ts?rgh-link-date=2021-06-23T15%3A19%3A24Z#L17) thinking

They might be setup tests that they ran "once" when they opened a PR.

**Comment by maaland** [comment]
> > Actually, are the tests in this file even run? I see that the top-level describe is [skipped](https://github.com/cognitedata/cognite-sdk-js/blob/master/packages/stable/src/__tests__/api/files.int.spec.ts?rgh-link-date=2021-06-23T15%3A19%3A24Z#L17) thinking
> 
> They might be setup tests that they ran "once" when they opened a PR.

Doubt it, as the entire outer `describe` containing the tests is skipped (`describe.skip`), meaning it should not run. Confirm by looking at the `test` section of the  [checks](https://github.com/cognitedata/cognite-sdk-js/runs/2895123071?check_suite_focus=true) of the PR. Does not look like this test suite is run, unless I'm missing something.

**Review by maaland — APPROVED** [review]

**Review by bdimitrijoski — APPROVED** [review]

**Pull request merged**
