### PR TITLE
chore: back in time

### PR DESCRIPTION
**Pull request by cognite-ornellas**

### CODE REVIEW

**Comment by andersfylling** [comment]
Can someone explain what the purpose of this PR is? I don't quite understand why my work on code generation is being reverted, along with work on the vision service, as all this is highly relevant work.

**Comment by cognite-ornellas** [comment]
> Expected — Waiting for status to be reported

Hey @BugGambit , this is just for investigation purposes only and wont be merged

**Comment by BugGambit** [comment]
@cognite-ornellas Why the need to create a PR for it?

**Comment by cognite-ornellas** [comment]
> @cognite-ornellas Why the need to create a PR for it?

@BugGambit for some reason there was some dificulties in replicating a specific behaviour locally. Sorry for that.

**Pull request closed without merging**
