### PR TITLE
Add missing 3D file fields

### PR DESCRIPTION
**Pull request by nsunderland-cognite**
You can see it documented here https://doc.cognitedata.com/api/0.6/#operation/getRevision

And here https://doc.cognitedata.com/api/0.6/#operation/getSectors

### CODE REVIEW

**Comment by ghost** [comment]
@nsunderland-cognite Can you update the test data as well?

**Comment by ghost** [comment]
Thanks btw

**Comment by nsunderland-cognite** [comment]
Done. That field should've been optional but I've added to the test data anyway.

**Comment by ghost** [comment]
You probably want to bump the package as well (patch). See the readme file for a guide

**Review by ghost — APPROVED** [review]
LGTM

**Pull request merged**
