### PR TITLE
docs(auth): fix function name

### PR DESCRIPTION
**Pull request by polomani**

### CODE REVIEW

**Comment by polomani** [comment]
@f1cognite I didn't change the last line, maybe github bug?

**Comment by hhenriques** [comment]
> @f1cognite I didn't change the last line, maybe github bug?

It's related to end-of-file encoding of Mac vs Windows. It happens to me when I make changes to a file created by someone who uses Mac.

**Comment by polomani** [comment]
@hhenriques annoying :(

**Review by ghost — APPROVED** [review]

**Pull request merged**
