### PR TITLE
fix: file upload for browsers

### PR DESCRIPTION
**Pull request by mrtraser**
fix issue mentioned by @maksnester in https://github.com/cognitedata/cognite-sdk-js/pull/427/files#r525184850

### CODE REVIEW

**Review by maksnester — APPROVED** [review]
If it works then it looks good to me 🙂 👍  Looking forward to the 1.0.3 core patch with that.

**Review by polomani — APPROVED** [review]
it's a 2-line dependency which has a pr that converts it to 1-liner
man I love js :joy:

**Comment by polomani** [comment]
do we need to release it right away? in that case remember the `[release]`

**Comment by maksnester** [comment]
@polomani @mrtraser yes, it would be great to release it asap since now it's totally broken

**Review by andreavs — APPROVED** [review]

**Pull request merged**
