### PR TITLE
feat(annotations): generate annotations for isolation planning app

### PR DESCRIPTION
**Pull request by SudilHasithaCognite**
Add IsoPlan annotations to be consistent with migration.

References:

- https://github.com/cognitedata/annotation-types/pull/136
- https://github.com/cognitedata/annotation-types/pull/157
- https://github.com/cognitedata/context-api/pull/4057
- https://github.com/cognitedata/service-contracts/pull/2505

### CODE REVIEW

**Comment by SudilHasithaCognite** [comment]
[This](https://github.com/cognitedata/cognite-sdk-js/commit/75b026e0d12e834a1feaab2582f4e417e9e449ad) commit causing some tests failures related to data-models.

**Comment by SudilHasithaCognite** [comment]
@andersfylling could you please review and approve this PR. Thanks in advance.

**Comment by SudilHasithaCognite** [comment]
@cognitedata/vision-team could you please review and approve this PR? Thanks in advance.

**Review by olacognite — APPROVED** [review]
LGTM, some doc strings seem to have fallen out for some reason, not only for isoplan types. Likely due to an earlier update?

**Pull request merged**
