### PR TITLE
chore(stable): fix CVE issue

### PR DESCRIPTION
**Pull request by sou1est**

### CODE REVIEW

**Comment by andersfylling** [comment]
Could you provide some more insight into this problem you've solved? Did you run a script that we can add in github actions?

**Comment by andersfylling** [comment]
I'm not sure I understand this change. What is this empty key?
image

Also note that, with the workspaces here the idea is to define all dependencies in the root, and let lerna package and link everything. At least, that's my mental model of how this is supposed to work, but I think cdf UX could confirm/deny this.

**Comment by sou1est** [comment]
> I'm not sure I understand this change. What is this empty key? image
> 
> Also note that, with the workspaces here the idea is to define all dependencies in the root, and let lerna package and link everything. At least, that's my mental model of how this is supposed to work, but I think cdf UX could confirm/deny this.

I just ran `npm audit fix`. But I was surprised that some of the packages use `package-lock.json` while the root of the project relies on yarn workspaces. All of the changes are generated so not sure of empty keys over there

**Comment by sou1est** [comment]
@andersfylling somehow both `core` and `stable` packages ended up with package-lock.json files instead of looking up at the root level `yarn.lock`. Looking at the git history it happened somewhat year ago.

**Comment by sou1est** [comment]
@andersfylling Now I think removing package.lock json should actually be fine, and it should as well fix CVEs i hope

**Comment by andersfylling** [comment]
> @andersfylling Now I think removing package.lock json should actually be fine, and it should as well fix CVEs i hope

I agree. That sounds like the right thing to do.

**Review by bkuzma — APPROVED** [review]

**Pull request merged**
